In [6]:
import pandas as pd
import numpy as np
import kagglehub

path = kagglehub.dataset_download("srisyra02/online-food-ordering-dataset")
print("Path to dataset files:", path)

Path to dataset files: C:\Users\Siddhi Lagad\.cache\kagglehub\datasets\srisyra02\online-food-ordering-dataset\versions\1

In [7]:
import os
print(os.listdir(path))

['online food delivery dataset.csv']

In [9]:
df = pd.read_csv(path + "/online food delivery dataset.csv")
df.head()

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Customer Type,latitude,longitude,Pin code,Output,Feedback,Unnamed: 13
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,Yes

In [10]:
print("First 5 rows:")
print(df.head())

print("\nShape (rows, columns):", df.shape)

print("\nColumn names:", df.columns.tolist())

print("\nData types:\n", df.dtypes)

First 5 rows:
   Age  Gender Marital Status Occupation  Monthly Income  \
0   20  Female         Single    Student       No Income
1   24  Female         Single    Student  Below Rs.10000
2   22    Male         Single    Student  Below Rs.10000
3   22  Female         Single    Student       No Income
4   22    Male         Single    Student  Below Rs.10000

  Educational Qualifications  Family size Customer Type  latitude  longitude  \
0              Post Graduate            4      Frequent   12.9766    77.5993
1                   Graduate            3       Regular   12.9770    77.5773
2              Post Graduate            3       Regular   12.9551    77.6593
3                   Graduate            6      Frequent   12.9473    77.5616
4              Post Graduate            4      Frequent   12.9850    77.5533

   Pin code Output   Feedback Unnamed: 13
0    560001    Yes   Positive         Yes
1    560009    Yes   Positive         Yes
2    560017    Yes  Negative          Yes
3    560019    Yes   Positive         Yes
4    560010    Yes   Positive         Yes

Shape (rows, columns): (388, 14)

Column names: ['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income', 'Educational Qualifications', 'Family size', 'Customer Type', 'latitude', 'longitude', 'Pin code', 'Output', 'Feedback', 'Unnamed: 13']

Data types:
 Age                             int64
Gender                            str
Marital Status                    str
Occupation                        str
Monthly Income                    str
Educational Qualifications        str
Family size                     int64
Customer Type                     str
latitude                      float64
longitude                     float64
Pin code                        int64
Output                            str
Feedback                          str
Unnamed: 13                       str
dtype: object

In [11]:
avg_age = df['Age'].mean()
min_age = df['Age'].min()
max_age = df['Age'].max()
male_count = (df['Gender'] == 'Male').sum()
female_count = (df['Gender'] == 'Female').sum()

print("Average age:", avg_age)
print("Minimum age:", min_age)
print("Maximum age:", max_age)
print("Male customers:", male_count)
print("Female customers:", female_count)

Average age: 24.628865979381445
Minimum age: 18
Maximum age: 33
Male customers: 222
Female customers: 166

In [12]:
filtered = df[(df['Age'] > 25) & (df['Occupation'] == 'Employee')]
filtered[['Age', 'Gender', 'Occupation', 'Monthly Income']]

     Age  Gender Occupation   Monthly Income
5     27  Female   Employee  More than 50000
16    28  Female   Employee   25001 to 50000
58    31    Male   Employee  More than 50000
90    27  Female   Employee   25001 to 50000
98    26    Male   Employee   25001 to 50000
..   ...     ...        ...              ...
369   30    Male   Employee  More than 50000
371   28    Male   Employee   25001 to 50000
375   26  Female   Employee   Below Rs.10000
377   31    Male   Employee   Below Rs.10000
380   27  Female   Employee  More than 50000

[73 rows x 4 columns]

In [16]:
avg_age_by_occupation = df.groupby('Occupation')['Age'].mean()
print(avg_age_by_occupation)

highest_occupation = avg_age_by_occupation.idxmax()
print("\nOccupation with highest average age:", highest_occupation)

Occupation
Employee          26.576271
House wife        30.333333
Self Employeed    26.388889
Student           22.811594
Name: Age, dtype: float64

Occupation with highest average age: House wife

In [18]:
feedback_counts = df['Feedback'].value_counts()
print(feedback_counts)

positive_pct = (feedback_counts.get('Positive', 0) / len(df)) * 100
print("\nPercentage positive feedback:", round(positive_pct, 2), "%")

Feedback
Positive     317
Negative      71
Name: count, dtype: int64

Percentage positive feedback: 81.7 %

In [19]:
occupation_feedback = df.groupby(['Occupation', 'Feedback']).size()
print(occupation_feedback)

Occupation      Feedback
Employee        Negative      33
                Positive      85
House wife      Negative       1
                Positive       8
Self Employeed  Negative      16
                Positive      38
Student         Negative      21
                Positive     186
dtype: int64

In [21]:
class BankAccount:

    def __init__(self, owner, balance):
        self.owner = owner
        self.balance = balance

In [23]:
account1.owner = "siddhi"
account1.balance = 1000

print (account1.owner)
print (account1.balance)

siddhi
1000

In [31]:
class BankAccount:
    def __init__(self, account_num, owner, balance):
        self.account_num = account_num
        self.owner = owner
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount

acc = BankAccount(103, "Aman", 2000)
acc.deposit(1000)
print("After deposit:", acc.balance)

acc.withdraw(500)
print("After withdrawal:", acc.balance)

After deposit: 3000
After withdrawal: 2500

In [33]:
class BankAccount:
    def __init__(self, account_num, owner, balance):
        self.account_num = account_num
        self.owner = owner
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
            return True
        else:
            return False

acc = BankAccount(104, "Neha", 1000)

result1 = acc.withdraw(400)
print("Valid withdrawal result:", result1, "| Balance:", acc.balance)

result2 = acc.withdraw(2000)
print("Overdraw withdrawal result:", result2, "| Balance:", acc.balance)

Valid withdrawal result: True | Balance: 600
Overdraw withdrawal result: False | Balance: 600

In [40]:
class Student:
    def __init__(self, name, rollno, marks):
        self.name = name
        self.rollno = rollno
        self.marks = marks
    def average_marks(self):
        return sum(self.marks) / len(self.marks)


student1 = Student("siddhi", 16,[ 70,80,90])
student2 = Student("Alice", 18, [90, 85, 95])
student3 = Student("neha", 17, [88, 92, 85])

print(student1.name)
print(student2.name)
print(student3.name)


for s in [student1, student2, student3]:
    print(f"{s.name}'s average marks: {s.average_marks():.2f}")

siddhi
Alice
neha
siddhi's average marks: 80.00
Alice's average marks: 90.00
neha's average marks: 88.33

In [42]:
class Vehicle:
    def __init__(self, brand, model,):
        self.brand = brand
        self.model = model

    def move(self):
        print(f"{self.brand} {self.model} is moving.")

class Car(Vehicle):
    pass

car = Car("Toyota","Innova")
car.move()

Toyota Innova is moving.

In [43]:
class Vehicle:
    def move(self):
        print("Vehicle is moving")

class Car(Vehicle):
    def move(self):
        print("Car is driving on the road")

class Boat(Vehicle):
    def move(self):
        print("Boat is sailing on water")

v = Vehicle()
c = Car()
b = Boat()

v.move()
c.move()
b.move()

Vehicle is moving
Car is driving on the road
Boat is sailing on water

In [44]:
class Vehicle:
    def __init__(self, brand):
        self.brand = brand

class Car(Vehicle):
    def __init__(self, brand, doors):
        super().__init__(brand)
        self.doors = doors

car1 = Car("Honda", 4)
car2 = Car("Ferrari", 2)

print(f"{car1.brand} - {car1.doors} doors")
print(f"{car2.brand} - {car2.doors} doors")

Honda - 4 doors
Ferrari - 2 doors

In [45]:
class Car:
    def move(self):
        print("Car drives on the road")

class Boat:
    def move(self):
        print("Boat sails on water")

class Airplane:
    def move(self):
        print("Airplane flies in the sky")

vehicles = [Car(), Boat(), Airplane()]

for vehicle in vehicles:
    vehicle.move()

Car drives on the road
Boat sails on water
Airplane flies in the sky